name: CLibBasic
version: 1.1
main: vip.creatio.basic.internal.CLibBasicBootstrap
api-version: 1.13
author: HenryRenYz
description: A basic lib plugin for creatio plugins

commands:
  clibbasictest:
    description: '123'
